version: 1.0.0 ({build})

environment:
  USER: Aculeasis
  PASS:
    secure: NXpVCVAyLyMPdL54/WFkOrkppluQsAv2fFjp2MfhBTotpmve/Mv4gjDD/RDmSWzx

  matrix:
    - PYTHON: C:\Python35
    - PYTHON: C:\Python35-x64
    - PYTHON: C:\Python37
    - PYTHON: C:\Python37-x64
    - PYTHON: C:\Python36
      DEPLOY: true
    - PYTHON: C:\Python36-x64
      DEPLOY: true

matrix:
  fast_finish: true

clone_depth: 1

init:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

install:
  - python -m pip install --upgrade wheel
  - pip install rhvoice-wrapper-data
  - pip install scons lxml
  - appveyor DownloadFile "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/unsis/nsis-2.46.5-Unicode-setup.exe" -FileName nsis.exe
  - nsis.exe /S
  - appveyor AddMessage "Preparation success"

build:
  verbosity: quiet

build_script:
  - mkdir github
  - python setup.py bdist_wheel bdist_wininst --dist-dir=github
  - appveyor AddMessage "Build success"

test_script:
  - cd dist
  - dir
  - for %%f in (rhvoice_wrapper_bin*.whl) do pip install %%f
  - cd ..
  - git clone --depth=1 https://github.com/Aculeasis/rhvoice-proxy
  - cd rhvoice-proxy
  - python -m unittest discover -v -s rhvoice_wrapper\tests
  - appveyor AddMessage "Testing success"
  - cd ..

artifacts:
  - path: github\*
    name: exe

before_deploy:
  - if [%APPVEYOR_REPO_TAG%]==[true] if [%DEPLOY%]==[true] pip install twine
  - if [%APPVEYOR_REPO_TAG%]==[true] if [%DEPLOY%]==[true] twine upload --skip-existing -u %USER% -p %PASS% dist/* & appveyor AddMessage "Deploy success" || appveyor AddMessage "Deploy failed"

deploy:
  - provider: GitHub
    auth_token:
      secure: ctp+XBxvU4Q/6f55WYYIxUF06CAkiuO3VTUshHz4XWsC/sKTrQyQodIEkgfhvIPF
    on:
      branch: master
      appveyor_repo_tag: true
      DEPLOY: true
