language:
  python

matrix:
  fast_finish: true
  include:
  - python: '3.4'
  - python: '3.5'
  - python: '3.6'
    env: DEPLOY=true

sudo: true

git:
  depth: 1

before_install:
  - sudo apt-get update -y
  - sudo apt-get -y install --no-install-recommends lame python3 locales opus-tools
  - sudo apt-get -y install --no-install-recommends scons build-essential python3-pip

install:
  - pip install setuptools wheel
  - pip install rhvoice-wrapper-data

before_script:
  - sudo locale-gen ru_RU.UTF-8
  - python setup.py sdist
  - git clone --depth=1 https://github.com/Aculeasis/rhvoice-proxy

script:
  - pip install dist/*
  - cd rhvoice-proxy/
  - export LD_LIBRARY_PATH=$(pip show rhvoice-wrapper-bin | grep Location | awk '{print $2}')/rhvoice_wrapper_bin/lib/
  - python -m unittest discover -v -s rhvoice_wrapper/tests/
  - cd ..

deploy:
  provider: pypi
  user: Aculeasis
  password:
    secure: k+EyXaWzcqiwWtv15VfRMCmdSjY/bAF6aaymZZX1Ur90wPMOr+Ax6ggrVFuOa7GbHRRKRaMOOa1kfQlLK7fvSP4P3EHjcz/yblfu8ivbqC5Kvy/LJeat0NOerWiGYUhvH90D/l3D6E72pXXCenBcixOC/fB+/SKV3r5E6r140LY42+7br1Kpvip8QB6EPuZ0/cKLoayrZ8sy8cjpKm5b/6HHwmT8tlZR9JH+MZj0mvRYBz63kzZNqcrKVAca09AyW/kLIQDr1KReHFfLO/UGsIkF3isMVYmZGDaGjTwpc8oFhIQUPZr6i0fynL3DdAA6y3uu7HvHXj3z+QBVJxYNH98i+88IZVuzR5OHsWe9xT6tfbOA36d6p/p4/iGDlkxSm/s6zeIRE6y+05aE7H4lgNYN+ObUTkc6QS59pyaDyJ4SSUP5XOerZzZfl13b6TtCrYnjMnBxMxNPoe9IdS/DnNWAVXTz9Mf5iPx4w5t89KqebLlKrudtFtvjfAme8v5TTFJUgjTC1YMu/5K3DYYdFMFfiJ8WeLRrkrioLQejSpgcs8T5QVMOfo5Ob4o4lhpmO5+TBQBEukHE71+byMqWDhgBAFSpy6SZxHKIwl2ec3UWNZOKOCDC8C8P8ibwBYwyesngFtgZEncITuJh2fY5IwaAgiji7Jsb3pEFPpKGCHA=
  skip_cleanup: true
  distributions: sdist
  skip_existing: true
  on:
    tags: true
    branch: master
    condition: "$DEPLOY == true"
